[project]
name = 'crowdfunding'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.crowdfundingv2]
path = 'crowdfunding.clar'
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 2
parser_version = 2